### ISSUE TITLE
Can we get a Google Sheet version of this repo that remains in sync with this table?

### ISSUE THREAD

**Issue by a37h** [Pitt-CSC/NewGrad-2021#105]
Hey!

Is it possible to get a Google Sheet version of this repo (that remains in sync with this table), same as in [the internships one](https://github.com/Pitt-CSC/Summer2021-Internships)?

**Comment by Zmwang622** [comment]
@varughese you wanna do it

**Comment by varughese** [comment]
@a37h do you want to take a stab at this? if you look at the internships repo you can copy the sync.py code and the github workflow. it could be a good learning experience
