### ISSUE TITLE
Positions no longer accept application

### ISSUE THREAD

**Issue by menglulul** [Pitt-CSC/NewGrad-2021#136]
Hi! I was looking at the list and found some of these links are pointing to nothing or show "no longer accept application". Here are the companies I found with unavailable links: ADP, Brex, belveder, Collins Aerospace, Credera, leetcode(the link looks okay but leetcode is actually not showing this position in its job page), hubspot, twiliow, vanguard.

**Comment by sbrmn96** [comment]
Leetcode works fine

**Comment by InfernapeXavier** [comment]
@sbrmn96 I think they mean that the posting is no longer on the LeetCode jobs page. I think they just haven't deactivated the link.

**Comment by Zmwang622** [comment]
yeah ill try to fix them soon, but no guarantees bc p swamped rn. If anyone wants to make a PR please doo

**Comment by InfernapeXavier** [comment]
@Zmwang622 I'm on it
